export const robots = [
    {
        id: 1,
        name: 'KingTchalla',
        username: 'King',
        email: 'KingTchalla@gmail.com',
    },
    {
        id: 2,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 3,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 4,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 5,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 6,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 7,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 8,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 9,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 10,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 11,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 12,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 13,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 14,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 15,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
    {
        id: 16,
        name: 'KingTchall',
        username: 'King',
        email: 'KingTchall@gmail.com',
    },
]