export const robots = [
    {
        id: 1,
        name: 'KingTchalla',
        username: 'King',
        email: 'KingTchalla@gmail.com',
    },
    {
        id: 2,
        name: 'JamesCamron',
        username: 'James',
        email: 'James@gmail.com',
    },
    {
        id: 3,
        name: 'CelineDion',
        username: 'Celine',
        email: 'Celine@gmail.com',
    },
    {
        id: 4,
        name: 'PaulWalker',
        username: 'Paul',
        email: 'Paul@gmail.com',
    },
    {
        id: 5,
        name: 'WiZkhalifa',
        username: 'Wiz',
        email: 'Wiz@gmail.com',
    },
    {
        id: 6,
        name: 'NarutoUzumaki',
        username: 'Naruto',
        email: 'Naruto@gmail.com',
    },
    {
        id: 7,
        name: 'MadaraUchicha',
        username: 'Madara',
        email: 'Madara@gmail.com',
    },
    {
        id: 8,
        name: 'KakashiHatake',
        username: 'Kakashi',
        email: 'Kakashi@gmail.com',
    },
    {
        id: 9,
        name: 'MinatoKamikaze',
        username: 'Minato',
        email: 'Minato@gmail.com',
    },
    {
        id: 10,
        name: 'StephenHawking',
        username: 'Stephen',
        email: 'Stephen@gmail.com',
    },
    {
        id: 11,
        name: 'RobertNoyce',
        username: 'Robert',
        email: 'Robert@gmail.com',
    },
    {
        id: 12,
        name: 'WalterIssacson',
        username: 'Walter',
        email: 'Walter@gmail.com',
    },
    {
        id: 13,
        name: 'SteveJobs',
        username: 'Steve',
        email: 'Steve@gmail.com',
    },
    {
        id: 14,
        name: 'ElonMusk',
        username: 'Elon',
        email: 'Elon@gmail.com',
    },
    {
        id: 15,
        name: 'BillGates',
        username: 'Bill',
        email: 'Bill@gmail.com',
    },
    {
        id: 16,
        name: 'GaryKindall',
        username: 'Gary',
        email: 'Gary@gmail.com',
    },
]